spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/book_rental
    username: postgres
    password: backend
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
